package com.svc.ventas.models.enums;

public enum Permission {

  VER_EMPRESAS,
  GESTIONAR_EMPRESAS,

  VER_PRODUCTOS,
  CREAR_PRODUCTOS,
  EDITAR_PRODUCTOS,
  ELIMINAR_PRODUCTOS,
  EDITAR_ESTADO_PRODUCTOS,

  VER_SUCURSALES,
  CREAR_SUCURSALES,
  EDITAR_SUCURSALES,
  ELIMINAR_SUCURSALES,

  VER_EMPLEADOS,
  CREAR_EMPLEADOS,
  EDITAR_EMPLEADOS,
  ELIMINAR_EMPLEADOS,
  EDITAR_ESTADO_EMPLEADOS,

  VER_PERSONAS,
  CREAR_PERSONAS,
  EDITAR_PERSONAS,
  ELIMINAR_PERSONAS,

  VER_USUARIOS,
  CREAR_USUARIOS,
  EDITAR_USUARIOS,
  ELIMINAR_USUARIOS,
  EDITAR_ESTADO_USUARIOS,

  VER_CLIENTES,
  CREAR_CLIENTES,
  EDITAR_CLIENTES,
  ELIMINAR_CLIENTES,

  VER_SERIES,
  CREAR_SERIES,
  EDITAR_SERIES,
  ELIMINAR_SERIES,
  TIPO_DOCUMENTOS_SERIES,
  CORRELATIVO_SERIES,

  VER_PRODUCTO_STOCK,
  EDITAR_PRODUCTO_STOCK,

  VER_PROVEEDORES,
  CREAR_PROVEEDORES,
  EDITAR_PROVEEDORES,

  VER_INVENTARIO,
  EDITAR_ESTADO_INVENTARIO,
  AJUSTAR_PRECIOS,

  VER_KARDEX,

  VER_CATEGORIAS,
  CREAR_CATEGORIAS,
  EDITAR_CATEGORIAS,
  ELIMINAR_CATEGORIAS,

  VER_COMPRAS,
  REGISTRAR_COMPRA,

  VER_VENTAS,
  REGISTRAR_VENTA,
  ANULAR_VENTA,

  VER_CAJA,
  APERTURAR_CAJA,
  CERRAR_CAJA,

  VER_REPORTES

}