version: "3.9"

services:
  svc-ventas:
    image: eclipse-temurin:17-jre
    container_name: svc-ventas
    restart: always
    working_dir: /opt/app
    volumes:
      - ./svc-ventas.jar:/opt/app/svc-ventas.jar
      - ./config:/config
    env_file:
      - .env
    ports:
      - "8085:8085"
    command: >
      java -jar svc-ventas.jar
      --spring.config.location=file:/config/
    networks:
      - app-net

networks:
  app-net:
    driver: bridge