server:
  port: 8085
spring:
  application:
    name: svc-ventas
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    #url: jdbc:mysql://mysql_bd_ventas:3306/bd_svc-ventas?serverTimezone=UTC
    url: jdbc:mysql://localhost:3314/db_ventas_v2?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      pool-name: namePool
    tomcat: 
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  sql:
    init:
      mode: always
      continue-on-error: true
token:
  apis:
    externa: apis-token-11190.XuZgRhBonrjpjA5JmQdGWN5mlOfUhujN
logging:
  level:
    org:
      hibernate:
        SQL: OFF
    #root: debug
key:
  signature: Ub4GiF7+MS8VG8s8Wh/6W/Uwu1LYqsRpVFDugnSlcphOuLHPsyiaEi+Xo0ARBjEDCNfujsWTKEluKyvvSpV0Qg==